### ISSUE TITLE
Increase column min width from 50px to at least 100px

### ISSUE THREAD

**Issue by aleksfront** [ixrock/mobx-react-table-grid#9]
Current minimum size too small for meaningful view. This is visible while doing table resize.

<img width="879" alt="small min-width" src="https://github.com/ixrock/mobx-react-table-grid/assets/9607060/eaa08b52-118b-42fb-b4c0-0e4a591067b3">

**Comment by aleksfront** [comment]
Can be changed in styles.

**Comment by ixrock** [comment]
**Solution how to setup default columns min-size:**

```css
.Table { --grid-col-size: minmax(100px, 1fr); }
```
